# .streamlit/secrets.toml
#DEEPSEEK_API_KEY = "sk-c8916cf861cf489c8e65ec31fabb11e4"
ZHIPU_API_KEY = "5b7e2ca340a443a9a977d439b5d5f67a.rLhVadGbKQiIVo3H"
#ALIYUN_API_KEY = "你的阿里云-Key"
#BAIDU_API_KEY = "你的百度-Key"
